services:
  - type: web
    name: breast-cancer-prediction-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app -w 4 -b 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    routes:
      - type: http
        path: /
