services:
  - type: web
    name: breast-cancer-prediction-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python model/train.py
    startCommand: gunicorn api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
